name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU (for multi-arch)
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Default build (all platforms supported by host / default)
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          endikablanco/deuspotify:latest
          endikablanco/deuspotify:${{ github.sha }}

    # ARM64-specific build
    - name: Build and push Docker image for ARM64
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/arm64/v8
        tags: |
          endikablanco/deuspotify:latest-arm64
          endikablanco/deuspotify:${{ github.sha }}-arm64
        cache-from: type=registry,ref=endikablanco/deuspotify:cache-arm64
        cache-to: type=registry,ref=endikablanco/deuspotify:cache-arm64,mode=max
